# action.yml
name: 'Hello World'
description: 'greet somebody'
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: 'world'
  # repository:
  #   description: 'what repo to checkout'
  #   required: true
  # ref:
  #   description: 'what ref to checkout'
  #   required: true
  # token:
  #   description: 'what token to use when checking out'
  #   required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    # - ${{ inputs.repository }}
    # - ${{ inputs.ref }}
    # - ${{ inputs.token }}
