# action.yml
name: 'Style check'
description: 'Checks code style and posts comments with suggestions.'
inputs:
  github_token:
    description: 'GitHub token that will be used to post style suggestion comments.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
